In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [17]:
-np.einsum('i,j->ij', a, b)

array([[ -2,  -3,  -4,  -5],
       [ -4,  -6,  -8, -10],
       [ -6,  -9, -12, -15],
       [ -8, -12, -16, -20]])

In [16]:
-t

array([[ -2,  -3,  -4,  -5],
       [ -4,  -6,  -8, -10],
       [ -2,  -3,  -4,  -5],
       [ -8, -12, -16, -20]])

In [9]:
np.einsum('i,ij->j', a, t)

array([ 48,  72,  96, 120])

In [14]:
np.sum(a[:, np.newaxis] * t, axis=0)

array([ 48,  72,  96, 120])

In [18]:
def sigmoid(x):
    """
    Compute the sigmoid function for the input here.
    Arguments:
    x -- A scalar or numpy array.
    Return:
    s -- sigmoid(x)
    """

    ### YOUR CODE HERE
    s = np.exp(x) / (np.exp(x) + 1)

    ### END YOUR CODE

    return s

In [22]:
x = -1
print(sigmoid(x))
x = np.array([2,3])
print(sigmoid(x))

0.2689414213699951
[0.88079708 0.95257413]
